version: '3'
services:
  hymnoscribe:
    image: revisoren/hymnoscripe:latest
    ports:
      - "9615:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER:-hymnoscribe}
      - DB_PASSWORD=${DB_PASSWORD:-hymnoscribe9715}
      - DB_NAME=${DB_NAME:-hymnoscribe}
      - URL=${URL:-https://hymnoscripe.godsapp.de}
      - SUPER_PASSWORD=${SUPER_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./migrations:/app/migrations
    command: sh -c "/app/run-migrations.sh && node server.js"
    depends_on:
      - db

  db:
    image: mysql:9.0
    volumes:
      - ./hymnoscribe_db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-hymnoscribe9715}
      MYSQL_DATABASE: ${DB_NAME:-hymnoscribe}
      MYSQL_USER: ${DB_USER:-hymnoscribe}
      MYSQL_PASSWORD: ${DB_PASSWORD:-hymnoscribe9715}
    
volumes:
  hymnoscribe_db:
  