name: Docker

on:
  push:
    branches: [ master, Loading-Optimization ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: revisoren
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          revisoren/hymnoscribe:${{ steps.branch-name.outputs.current_branch }}
          ${{ github.ref == 'refs/heads/master' && 'revisoren/hymnoscribe:latest' || '' }}
          ${{ github.ref == 'refs/heads/Loading-Optimization' && 'revisoren/hymnoscribe:beta' || '' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max