name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hymnoscripe:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: revisoren
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: revisoren/hymnoscripe:latest
